# Form implementation generated from reading ui file 'UI\ui_batchxlstoxlsx.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(620, 600)
        MainWindow.setMinimumSize(QtCore.QSize(620, 600))
        MainWindow.setMaximumSize(QtCore.QSize(620, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LokasiSumberFolder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LokasiSumberFolder_btn.setGeometry(QtCore.QRect(20, 50, 181, 25))
        self.LokasiSumberFolder_btn.setObjectName("LokasiSumberFolder_btn")
        self.listFileItems_lokasiSumber = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listFileItems_lokasiSumber.setGeometry(QtCore.QRect(20, 90, 581, 192))
        self.listFileItems_lokasiSumber.setObjectName("listFileItems_lokasiSumber")
        self.LokasiOutputFolder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LokasiOutputFolder_btn.setGeometry(QtCore.QRect(20, 300, 181, 25))
        self.LokasiOutputFolder_btn.setObjectName("LokasiOutputFolder_btn")
        self.listFileItems_lokasiTujuan = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listFileItems_lokasiTujuan.setGeometry(QtCore.QRect(20, 340, 581, 171))
        self.listFileItems_lokasiTujuan.setObjectName("listFileItems_lokasiTujuan")
        self.label_judul = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_judul.setGeometry(QtCore.QRect(30, 20, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        self.label_judul.setFont(font)
        self.label_judul.setObjectName("label_judul")
        self.label_copyright = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_copyright.setGeometry(QtCore.QRect(400, 560, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        self.label_copyright.setFont(font)
        self.label_copyright.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_copyright.setObjectName("label_copyright")
        self.textBrowser_lokasiSumber = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_lokasiSumber.setGeometry(QtCore.QRect(210, 50, 391, 31))
        self.textBrowser_lokasiSumber.setObjectName("textBrowser_lokasiSumber")
        self.textBrowser_lokasiTujuan = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_lokasiTujuan.setGeometry(QtCore.QRect(210, 300, 391, 31))
        self.textBrowser_lokasiTujuan.setObjectName("textBrowser_lokasiTujuan")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 550, 111, 25))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 520, 581, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.openFolderOutputXLSX_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openFolderOutputXLSX_btn.setGeometry(QtCore.QRect(140, 550, 111, 25))
        self.openFolderOutputXLSX_btn.setObjectName("openFolderOutputXLSX_btn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Batch Convert XLS to XLSX"))
        self.LokasiSumberFolder_btn.setText(_translate("MainWindow", "Lokasi Folder File .XLS"))
        self.LokasiOutputFolder_btn.setText(_translate("MainWindow", "Lokasi Output Folder File .XLSX"))
        self.label_judul.setText(_translate("MainWindow", "Batch Konversi xls ke xlsx"))
        self.label_copyright.setText(_translate("MainWindow", "@M. A / Ghissela Davinca Rhamadani"))
        self.textBrowser_lokasiSumber.setPlaceholderText(_translate("MainWindow", "Lokasi Folder Sumber File XLS Asli"))
        self.textBrowser_lokasiTujuan.setPlaceholderText(_translate("MainWindow", "Lokasi Folder Tujuan File XLSX"))
        self.pushButton.setText(_translate("MainWindow", "Mulai Konversi"))
        self.openFolderOutputXLSX_btn.setText(_translate("MainWindow", "Buka Folder XLSX"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
