# Form implementation generated from reading ui file 'UI\ui_main_app2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 702)
        MainWindow.setMinimumSize(QtCore.QSize(900, 702))
        MainWindow.setMaximumSize(QtCore.QSize(900, 702))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bg/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #fedb59;\n"
"    font: 10pt \"Roboto\";\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton {\n"
"    background-color: #FA7A21;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    padding: 5px 10px;    \n"
"    font: 10pt \"Roboto\";\n"
"    border-radius: 5px;\n"
"}\n"
"QListWidget {\n"
"    border-radius: 10px;\n"
"    background-color: #febd59;\n"
"    border: 1px solid #c06000;\n"
"    }\n"
"QTextEdit#textEditDragDropFiles {\n"
"    background-color: rgb(254, 188, 90);\n"
"    border-radius: 5px;\n"
"    border: 1px solid #c06000;\n"
"}\n"
"QPushButton#pengaturan_btn {\n"
"    border : none;\n"
"    background-color: rgb(192, 96, 0);\n"
"    border-radius : 12px;\n"
"    }\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BrowseFile_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BrowseFile_btn.setGeometry(QtCore.QRect(19, 120, 151, 30))
        self.BrowseFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.BrowseFile_btn.setObjectName("BrowseFile_btn")
        self.openFileFolder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openFileFolder_btn.setGeometry(QtCore.QRect(350, 620, 161, 30))
        self.openFileFolder_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.openFileFolder_btn.setObjectName("openFileFolder_btn")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(290, 430, 221, 30))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_PT = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_PT.setGeometry(QtCore.QRect(20, 80, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_PT.setFont(font)
        self.label_PT.setObjectName("label_PT")
        self.listItems_outputFilesXLSX = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_outputFilesXLSX.setGeometry(QtCore.QRect(170, 470, 341, 141))
        self.listItems_outputFilesXLSX.setStyleSheet("")
        self.listItems_outputFilesXLSX.setObjectName("listItems_outputFilesXLSX")
        self.listItems_filesSource = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_filesSource.setGeometry(QtCore.QRect(170, 280, 341, 141))
        self.listItems_filesSource.setStyleSheet("")
        self.listItems_filesSource.setObjectName("listItems_filesSource")
        self.isidansalinData_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.isidansalinData_btn.setGeometry(QtCore.QRect(169, 430, 111, 30))
        self.isidansalinData_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.isidansalinData_btn.setObjectName("isidansalinData_btn")
        self.textEditDragDropFiles = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditDragDropFiles.setGeometry(QtCore.QRect(20, 160, 491, 111))
        self.textEditDragDropFiles.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ClosedHandCursor))
        self.textEditDragDropFiles.setStyleSheet("")
        self.textEditDragDropFiles.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.textEditDragDropFiles.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.textEditDragDropFiles.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEditDragDropFiles.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEditDragDropFiles.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.textEditDragDropFiles.setObjectName("textEditDragDropFiles")
        self.cekValidasiFile_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cekValidasiFile_btn.setGeometry(QtCore.QRect(620, 530, 148, 50))
        self.cekValidasiFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.cekValidasiFile_btn.setStyleSheet("QPushButton#cekValidasiFile_btn{\n"
"    background-color: qlineargradient(spread:pad, x1:0.131, y1:0, x2:0.591, y2:1, stop:0 rgba(255, 85, 0, 255), stop:1 rgba(254, 189, 89, 255));\n"
"    border: 3px solid #ffffff;\n"
"}")
        self.cekValidasiFile_btn.setObjectName("cekValidasiFile_btn")
        self.konversiXLStoXLSX_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.konversiXLStoXLSX_btn.setGeometry(QtCore.QRect(620, 590, 148, 50))
        self.konversiXLStoXLSX_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.konversiXLStoXLSX_btn.setStyleSheet("QPushButton#konversiXLStoXLSX_btn {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0.642, y2:0.994, stop:0 rgba(255, 59, 10, 255), stop:1 rgba(254, 189, 89, 255));\n"
"    border: 3px solid #ffffff;\n"
"}")
        self.konversiXLStoXLSX_btn.setObjectName("konversiXLStoXLSX_btn")
        self.logoOT_img = QtWidgets.QLabel(parent=self.centralwidget)
        self.logoOT_img.setGeometry(QtCore.QRect(20, -10, 91, 111))
        self.logoOT_img.setPixmap(QtGui.QPixmap("bg/10.png"))
        self.logoOT_img.setScaledContents(True)
        self.logoOT_img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoOT_img.setObjectName("logoOT_img")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(520, 160, 361, 245))
        self.frame.setStyleSheet("QFrame { \n"
"    border: 1px solid #c06000;\n"
"    border-radius: 8px;\n"
"    background-color: rgb(254, 189, 89);\n"
"    font: 500 9pt \"Roboto Medium\";\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.fillWarnaSuhu2_label = QtWidgets.QLabel(parent=self.frame)
        self.fillWarnaSuhu2_label.setGeometry(QtCore.QRect(20, 210, 146, 25))
        self.fillWarnaSuhu2_label.setObjectName("fillWarnaSuhu2_label")
        self.WaktuHoldingLabel = QtWidgets.QLabel(parent=self.frame)
        self.WaktuHoldingLabel.setGeometry(QtCore.QRect(20, 120, 231, 25))
        self.WaktuHoldingLabel.setObjectName("WaktuHoldingLabel")
        self.fillWarnaHoldingTime_label = QtWidgets.QLabel(parent=self.frame)
        self.fillWarnaHoldingTime_label.setGeometry(QtCore.QRect(20, 150, 146, 25))
        self.fillWarnaHoldingTime_label.setObjectName("fillWarnaHoldingTime_label")
        self.pilihWarnaSuhu2_btn = QtWidgets.QPushButton(parent=self.frame)
        self.pilihWarnaSuhu2_btn.setGeometry(QtCore.QRect(170, 210, 81, 25))
        self.pilihWarnaSuhu2_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pilihWarnaSuhu2_btn.setText("")
        self.pilihWarnaSuhu2_btn.setObjectName("pilihWarnaSuhu2_btn")
        self.pilihWarnaHoldingTime_btn = QtWidgets.QPushButton(parent=self.frame)
        self.pilihWarnaHoldingTime_btn.setGeometry(QtCore.QRect(170, 150, 81, 25))
        self.pilihWarnaHoldingTime_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pilihWarnaHoldingTime_btn.setText("")
        self.pilihWarnaHoldingTime_btn.setObjectName("pilihWarnaHoldingTime_btn")
        self.batasRangeSuhu2EG710DerajatLabel = QtWidgets.QLabel(parent=self.frame)
        self.batasRangeSuhu2EG710DerajatLabel.setGeometry(QtCore.QRect(20, 90, 231, 25))
        self.batasRangeSuhu2EG710DerajatLabel.setObjectName("batasRangeSuhu2EG710DerajatLabel")
        self.pilihWarnaSuhu1_btn = QtWidgets.QPushButton(parent=self.frame)
        self.pilihWarnaSuhu1_btn.setGeometry(QtCore.QRect(170, 180, 81, 25))
        self.pilihWarnaSuhu1_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pilihWarnaSuhu1_btn.setText("")
        self.pilihWarnaSuhu1_btn.setObjectName("pilihWarnaSuhu1_btn")
        self.fillWarnaSuhu1_label = QtWidgets.QLabel(parent=self.frame)
        self.fillWarnaSuhu1_label.setGeometry(QtCore.QRect(20, 180, 146, 25))
        self.fillWarnaSuhu1_label.setObjectName("fillWarnaSuhu1_label")
        self.batasRangeSuhu2_DoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.batasRangeSuhu2_DoubleSpinBox.setGeometry(QtCore.QRect(260, 90, 81, 25))
        self.batasRangeSuhu2_DoubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.batasRangeSuhu2_DoubleSpinBox.setDecimals(1)
        self.batasRangeSuhu2_DoubleSpinBox.setProperty("value", 71.0)
        self.batasRangeSuhu2_DoubleSpinBox.setObjectName("batasRangeSuhu2_DoubleSpinBox")
        self.batasSuhu1Label = QtWidgets.QLabel(parent=self.frame)
        self.batasSuhu1Label.setGeometry(QtCore.QRect(20, 60, 231, 25))
        self.batasSuhu1Label.setObjectName("batasSuhu1Label")
        self.holdingTime_lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.holdingTime_lineEdit.setGeometry(QtCore.QRect(260, 120, 81, 25))
        self.holdingTime_lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.holdingTime_lineEdit.setObjectName("holdingTime_lineEdit")
        self.pengaturan_btn = QtWidgets.QPushButton(parent=self.frame)
        self.pengaturan_btn.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.pengaturan_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pengaturan_btn.setStyleSheet("")
        self.pengaturan_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bg/setting.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pengaturan_btn.setIcon(icon1)
        self.pengaturan_btn.setIconSize(QtCore.QSize(40, 40))
        self.pengaturan_btn.setObjectName("pengaturan_btn")
        self.batasSuhu1_DoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.frame)
        self.batasSuhu1_DoubleSpinBox.setGeometry(QtCore.QRect(260, 60, 81, 25))
        self.batasSuhu1_DoubleSpinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.batasSuhu1_DoubleSpinBox.setDecimals(1)
        self.batasSuhu1_DoubleSpinBox.setProperty("value", 40.0)
        self.batasSuhu1_DoubleSpinBox.setObjectName("batasSuhu1_DoubleSpinBox")
        self.yellow_original_img_5 = QtWidgets.QLabel(parent=self.frame)
        self.yellow_original_img_5.setGeometry(QtCore.QRect(280, 160, 54, 71))
        self.yellow_original_img_5.setPixmap(QtGui.QPixmap("bg/halal_logo.png"))
        self.yellow_original_img_5.setScaledContents(True)
        self.yellow_original_img_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.yellow_original_img_5.setObjectName("yellow_original_img_5")
        self.original_img = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img.setGeometry(QtCore.QRect(-30, 260, 241, 331))
        self.original_img.setPixmap(QtGui.QPixmap("bg/kiranti_original_yellow.png"))
        self.original_img.setScaledContents(True)
        self.original_img.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img.setObjectName("original_img")
        self.original_img_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_2.setGeometry(QtCore.QRect(470, 410, 241, 271))
        self.original_img_2.setPixmap(QtGui.QPixmap("bg/3.png"))
        self.original_img_2.setScaledContents(True)
        self.original_img_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_2.setObjectName("original_img_2")
        self.original_img_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_3.setGeometry(QtCore.QRect(-40, 500, 231, 321))
        self.original_img_3.setPixmap(QtGui.QPixmap("bg/1.png"))
        self.original_img_3.setScaledContents(True)
        self.original_img_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_3.setObjectName("original_img_3")
        self.original_img_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_6.setGeometry(QtCore.QRect(630, 340, 301, 421))
        self.original_img_6.setPixmap(QtGui.QPixmap("bg/5.png"))
        self.original_img_6.setScaledContents(True)
        self.original_img_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_6.setObjectName("original_img_6")
        self.original_img_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_7.setGeometry(QtCore.QRect(-30, 460, 141, 211))
        self.original_img_7.setPixmap(QtGui.QPixmap("bg/4.png"))
        self.original_img_7.setScaledContents(True)
        self.original_img_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_7.setObjectName("original_img_7")
        self.original_img_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_4.setGeometry(QtCore.QRect(710, 40, 181, 141))
        self.original_img_4.setPixmap(QtGui.QPixmap("bg/2.png"))
        self.original_img_4.setScaledContents(True)
        self.original_img_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_4.setObjectName("original_img_4")
        self.original_img_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.original_img_8.setGeometry(QtCore.QRect(390, -40, 211, 251))
        self.original_img_8.setPixmap(QtGui.QPixmap("bg/kiranti_logo.png"))
        self.original_img_8.setScaledContents(True)
        self.original_img_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.original_img_8.setObjectName("original_img_8")
        self.simpanPengaturan_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.simpanPengaturan_btn.setGeometry(QtCore.QRect(620, 420, 141, 40))
        self.simpanPengaturan_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.simpanPengaturan_btn.setObjectName("simpanPengaturan_btn")
        self.listItems_filesSource.raise_()
        self.logoOT_img.raise_()
        self.original_img_3.raise_()
        self.original_img_6.raise_()
        self.original_img_8.raise_()
        self.BrowseFile_btn.raise_()
        self.openFileFolder_btn.raise_()
        self.progressBar.raise_()
        self.label_PT.raise_()
        self.listItems_outputFilesXLSX.raise_()
        self.textEditDragDropFiles.raise_()
        self.frame.raise_()
        self.original_img_4.raise_()
        self.original_img_2.raise_()
        self.simpanPengaturan_btn.raise_()
        self.cekValidasiFile_btn.raise_()
        self.konversiXLStoXLSX_btn.raise_()
        self.original_img.raise_()
        self.original_img_7.raise_()
        self.isidansalinData_btn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionBatch_Convert_XLS_to_XLSX = QtGui.QAction(parent=MainWindow)
        self.actionBatch_Convert_XLS_to_XLSX.setObjectName("actionBatch_Convert_XLS_to_XLSX")
        self.actionValidation_XLS_XLSX = QtGui.QAction(parent=MainWindow)
        self.actionValidation_XLS_XLSX.setObjectName("actionValidation_XLS_XLSX")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saving Your Quality Time"))
        self.BrowseFile_btn.setText(_translate("MainWindow", "Pilih File / Folder .xlsx"))
        self.openFileFolder_btn.setText(_translate("MainWindow", "Buka Output Folder .xlsx"))
        self.label_PT.setText(_translate("MainWindow", "PT. CAYADEWI SEHAT INDONESIA ABADI"))
        self.isidansalinData_btn.setText(_translate("MainWindow", "ISI DATA EXCEL"))
        self.textEditDragDropFiles.setToolTip(_translate("MainWindow", "Jatuhkan File Excel .xlsx disini"))
        self.textEditDragDropFiles.setPlaceholderText(_translate("MainWindow", "Drag & Drop File .xlsx Disini ..."))
        self.cekValidasiFile_btn.setText(_translate("MainWindow", "Grafik Analisa"))
        self.konversiXLStoXLSX_btn.setText(_translate("MainWindow", "Konversi .xls Ke .xlsx"))
        self.fillWarnaSuhu2_label.setText(_translate("MainWindow", "Pilih Warna Suhu 2"))
        self.WaktuHoldingLabel.setText(_translate("MainWindow", " Waktu Holding Sheet Data ( HH:MM:SS)"))
        self.fillWarnaHoldingTime_label.setText(_translate("MainWindow", "Pilih Warna Holding Time"))
        self.batasRangeSuhu2EG710DerajatLabel.setText(_translate("MainWindow", "Batas Range Suhu 2 ( e.g. 71.0 derajat )"))
        self.fillWarnaSuhu1_label.setText(_translate("MainWindow", "Pilih Warna Suhu 1"))
        self.batasSuhu1Label.setText(_translate("MainWindow", "Batas Suhu 1 (e.g. 40.0 derajat )"))
        self.holdingTime_lineEdit.setPlaceholderText(_translate("MainWindow", "e.g. 00:09:00"))
        self.simpanPengaturan_btn.setText(_translate("MainWindow", "Simpan Konfigurasi"))
        self.actionBatch_Convert_XLS_to_XLSX.setText(_translate("MainWindow", "Batch Convert XLS to XLSX"))
        self.actionValidation_XLS_XLSX.setText(_translate("MainWindow", "Validation XLS - XLSX"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
