# Form implementation generated from reading ui file 'UI\ui_main_app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(520, 600))
        MainWindow.setMaximumSize(QtCore.QSize(520, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BrowseFile_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BrowseFile_btn.setGeometry(QtCore.QRect(20, 33, 140, 25))
        self.BrowseFile_btn.setObjectName("BrowseFile_btn")
        self.openFileFolder_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.openFileFolder_btn.setGeometry(QtCore.QRect(20, 530, 140, 25))
        self.openFileFolder_btn.setObjectName("openFileFolder_btn")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(150, 280, 351, 25))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_PT = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_PT.setGeometry(QtCore.QRect(20, 0, 301, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.label_PT.setFont(font)
        self.label_PT.setObjectName("label_PT")
        self.listItems_outputFilesXLSX = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_outputFilesXLSX.setGeometry(QtCore.QRect(20, 320, 481, 200))
        self.listItems_outputFilesXLSX.setObjectName("listItems_outputFilesXLSX")
        self.listItems_filesSource = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_filesSource.setGeometry(QtCore.QRect(20, 70, 481, 200))
        self.listItems_filesSource.setObjectName("listItems_filesSource")
        self.isidansalinData_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.isidansalinData_btn.setGeometry(QtCore.QRect(20, 280, 120, 25))
        self.isidansalinData_btn.setObjectName("isidansalinData_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.MenuBar_Setting = QtWidgets.QMenuBar(parent=MainWindow)
        self.MenuBar_Setting.setGeometry(QtCore.QRect(0, 0, 520, 22))
        self.MenuBar_Setting.setObjectName("MenuBar_Setting")
        self.menuTools_Tambahan = QtWidgets.QMenu(parent=self.MenuBar_Setting)
        self.menuTools_Tambahan.setObjectName("menuTools_Tambahan")
        MainWindow.setMenuBar(self.MenuBar_Setting)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBatch_Convert_XLS_to_XLSX = QtGui.QAction(parent=MainWindow)
        self.actionBatch_Convert_XLS_to_XLSX.setObjectName("actionBatch_Convert_XLS_to_XLSX")
        self.actionValidation_XLS_XLSX = QtGui.QAction(parent=MainWindow)
        self.actionValidation_XLS_XLSX.setObjectName("actionValidation_XLS_XLSX")
        self.menuTools_Tambahan.addAction(self.actionBatch_Convert_XLS_to_XLSX)
        self.menuTools_Tambahan.addAction(self.actionValidation_XLS_XLSX)
        self.MenuBar_Setting.addAction(self.menuTools_Tambahan.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Saving Your Quality Time"))
        self.BrowseFile_btn.setText(_translate("MainWindow", "Pilih File / Folder .xlsx"))
        self.openFileFolder_btn.setText(_translate("MainWindow", "Buka Output Folder .xlsx"))
        self.label_PT.setText(_translate("MainWindow", "PT. CAYADEWI SEHAT INDONESIA ABADI"))
        self.isidansalinData_btn.setText(_translate("MainWindow", "ISI DATA EXCEL"))
        self.menuTools_Tambahan.setTitle(_translate("MainWindow", "Tools Tambahan"))
        self.actionBatch_Convert_XLS_to_XLSX.setText(_translate("MainWindow", "Batch Convert XLS to XLSX"))
        self.actionValidation_XLS_XLSX.setText(_translate("MainWindow", "Validation XLS - XLSX"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
