# Form implementation generated from reading ui file 'UI\ui_validasixlsdanxlsx.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        MainWindow.setMinimumSize(QtCore.QSize(0, 700))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cekValidasi_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cekValidasi_btn.setGeometry(QtCore.QRect(10, 460, 181, 25))
        self.cekValidasi_btn.setObjectName("cekValidasi_btn")
        self.lokasiFolderSumberXLS = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lokasiFolderSumberXLS.setGeometry(QtCore.QRect(10, 40, 141, 25))
        self.lokasiFolderSumberXLS.setObjectName("lokasiFolderSumberXLS")
        self.text_lokasisumberfilesxls = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_lokasisumberfilesxls.setGeometry(QtCore.QRect(10, 70, 451, 31))
        self.text_lokasisumberfilesxls.setObjectName("text_lokasisumberfilesxls")
        self.listItems_FilesSumber_xls = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_FilesSumber_xls.setGeometry(QtCore.QRect(10, 110, 451, 131))
        self.listItems_FilesSumber_xls.setObjectName("listItems_FilesSumber_xls")
        self.lokasiFolderSumberXLSX = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lokasiFolderSumberXLSX.setGeometry(QtCore.QRect(10, 250, 141, 25))
        self.lokasiFolderSumberXLSX.setObjectName("lokasiFolderSumberXLSX")
        self.text_lokasitujuanfilesxlsx = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.text_lokasitujuanfilesxlsx.setGeometry(QtCore.QRect(10, 280, 451, 31))
        self.text_lokasitujuanfilesxlsx.setObjectName("text_lokasitujuanfilesxlsx")
        self.listItems_FilesSumber_xlsx = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listItems_FilesSumber_xlsx.setGeometry(QtCore.QRect(10, 320, 451, 131))
        self.listItems_FilesSumber_xlsx.setObjectName("listItems_FilesSumber_xlsx")
        self.detailDifferendData_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.detailDifferendData_btn.setGeometry(QtCore.QRect(470, 40, 191, 24))
        self.detailDifferendData_btn.setObjectName("detailDifferendData_btn")
        self.comboBox_dtsheet_xlsx = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_dtsheet_xlsx.setGeometry(QtCore.QRect(160, 250, 141, 22))
        self.comboBox_dtsheet_xlsx.setObjectName("comboBox_dtsheet_xlsx")
        self.tableView_outputDiffData = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_outputDiffData.setGeometry(QtCore.QRect(470, 70, 421, 581))
        self.tableView_outputDiffData.setObjectName("tableView_outputDiffData")
        self.comboBox_dtsheet_xls = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_dtsheet_xls.setGeometry(QtCore.QRect(160, 40, 131, 22))
        self.comboBox_dtsheet_xls.setObjectName("comboBox_dtsheet_xls")
        self.listView_itemsOutputs = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_itemsOutputs.setGeometry(QtCore.QRect(10, 520, 451, 131))
        self.listView_itemsOutputs.setObjectName("listView_itemsOutputs")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 490, 451, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_copyright = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_copyright.setGeometry(QtCore.QRect(580, 660, 301, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        self.label_copyright.setFont(font)
        self.label_copyright.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_copyright.setObjectName("label_copyright")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cek Kesamaan DATA xls dan xlsx"))
        self.cekValidasi_btn.setText(_translate("MainWindow", "Cek Kesamaan DATA XLS/XLSX"))
        self.lokasiFolderSumberXLS.setText(_translate("MainWindow", "Pilih Folder XLS"))
        self.text_lokasisumberfilesxls.setPlaceholderText(_translate("MainWindow", "Lokasi Sumber File Folder XLS"))
        self.lokasiFolderSumberXLSX.setText(_translate("MainWindow", "Pilih Folder XLSX"))
        self.text_lokasitujuanfilesxlsx.setPlaceholderText(_translate("MainWindow", "Lokasi Sumber File Folder XLSX"))
        self.detailDifferendData_btn.setText(_translate("MainWindow", "Klik Lihat Detail Perbedaan DATA"))
        self.label_copyright.setText(_translate("MainWindow", "@M. A / Ghissela Davinca Rhamadani"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec())
